export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const HOMEPAGE_UPDATE_EVENTS_INFO = 'HOMEPAGE_UPDATE_EVENTS_INFO';
export const HOMEPAGE_UPDATE_COURSES_INFO = 'HOMEPAGE_UPDATE_COURSES_INFO';
export const HOMEPAGE_UPDATE_DEPARTMENTS_INFO = 'HOMEPAGE_UPDATE_DEPARTMENTS_INFO';
export const HOMEPAGE_UPDATE_FACTS_INFO = 'HOMEPAGE_UPDATE_FACTS_INFO' 

export const COURSES_UPDATE_CLASS = 'COURSES_UPDATE_CLASS'

export const UPDATE_USER_LIST = 'UPDATE_USER_LIST';
export const DELETE_USER = 'DELETE_USER';